///////////////////////////////////////////////////////////////////////////////
//         Gigi Rapid Graphics Prototyping and Code Generation Suite         //
//        Copyright (c) 2024 Electronic Arts Inc. All rights reserved.       //
///////////////////////////////////////////////////////////////////////////////

ENUM_BEGIN(ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode, "")
    ENUM_ITEM(Off, "No reactive mask will be used")
    ENUM_ITEM(Generate, "Generative mask will be generated by FidelityFX SDK into the texture plugged into the reactive pin, and will be used during upscaling.")
    ENUM_ITEM(Custom, "Generative mask provided to the reactive pin will be used during upscale.")
ENUM_END()

ENUM_BEGIN(ExternalNode_AMD_FidelityFXSDK_Upscaling_Version, "")
    ENUM_ITEM(Default, "")
    ENUM_ITEM(v2_3_4, "Use 2.3.4")
    ENUM_ITEM(v3_1_5, "Use 3.1.5")
ENUM_END()

STRUCT_BEGIN(ValueOrVariable_Enum_ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode, "ValueOrVariable<ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode>")
    STRUCT_FIELD(ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode, value, ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode::Off, "The value to use if no variable given", 0)
    STRUCT_FIELD(VariableReference, variable, {}, "The variable to use", 0)
STRUCT_END()

STRUCT_BEGIN(ValueOrVariable_Enum_ExternalNode_AMD_FidelityFXSDK_Upscaling_Version, "ValueOrVariable<ExternalNode_AMD_FidelityFXSDK_Upscaling_Version>")
    STRUCT_FIELD(ExternalNode_AMD_FidelityFXSDK_Upscaling_Version, value, ExternalNode_AMD_FidelityFXSDK_Upscaling_Version::Default, "The value to use if no variable given", 0)
    STRUCT_FIELD(VariableReference, variable, {}, "The variable to use", 0)
STRUCT_END()

STRUCT_BEGIN(ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask, "")
    STRUCT_FIELD(ValueOrVariable_Enum_ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode, reactiveMaskMode, { ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask_ReactiveMaskMode::Off }, "Reactive mask setting", 0)
    STRUCT_FIELD(ValueOrVariable_Float, scale, { 1.0f }, "A value to scale the output", 0)
    STRUCT_FIELD(ValueOrVariable_Float, cutoffThreshold, { 0.2f }, "A threshold value to generate a binary reactive mask", 0)
    STRUCT_FIELD(ValueOrVariable_Float, binaryValue, { 0.9f }, "A value to set for the binary reactive mask", 0)

    STRUCT_FIELD(ValueOrVariable_Bool, APPLY_TONEMAP, { true }, "", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, APPLY_INVERSETONEMAP, { false }, "", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, APPLY_THRESHOLD, { true }, "", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, USE_COMPONENTS_MAX, { true }, "", 0)
STRUCT_END()

STRUCT_BEGIN(ExternalNode_AMD_FidelityFXSDK_Upscaling, "")
    STRUCT_FIELD(ValueOrVariable_Enum_ExternalNode_AMD_FidelityFXSDK_Upscaling_Version, version, { ExternalNode_AMD_FidelityFXSDK_Upscaling_Version::Default }, "FSR version to use", 0)

    STRUCT_STATIC_ARRAY(unsigned int, initialMaxRenderSize, 2, { 0 COMMA 0 }, "The initial maximum render size. The context will be created as the maximum of this, and the color pin resource.", 0)
    STRUCT_STATIC_ARRAY(unsigned int, initialMaxUpscaleSize, 2, { 0 COMMA 0 }, "The initial maximum upscale size. The context will be created as the maximum of this, and the output pin resource.", 0)

    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_HIGH_DYNAMIC_RANGE, { true }, "A bit indicating if the input color data provided is using a high-dynamic range.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DISPLAY_RESOLUTION_MOTION_VECTORS, { false }, "A bit indicating if the motion vectors are rendered at display resolution.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_MOTION_VECTORS_JITTER_CANCELLATION, { false }, "A bit indicating that the motion vectors have the jittering pattern applied to them.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DEPTH_INVERTED, { true }, "A bit indicating that the input depth buffer data provided is inverted [1..0].", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DEPTH_INFINITE, { false }, "A bit indicating that the input depth buffer data provided is using an infinite far plane.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_AUTO_EXPOSURE, { false }, "A bit indicating if automatic exposure should be applied to input color data.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DYNAMIC_RESOLUTION, { false }, "A bit indicating that the application uses dynamic resolution scaling.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DEBUG_CHECKING, { false }, "A bit indicating that the runtime should check some API values and report issues.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_NON_LINEAR_COLORSPACE, { false }, "A bit indicating that the color resource contains perceptual (gamma corrected) colors", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, ENABLE_DEBUG_VISUALIZATION, { false }, "A bit indicating if debug visualization is allowed. (memory consumption could increase)", 0)

    STRUCT_FIELD(NodePinReference, color, {}, "Color buffer for the current frame (at render resolution).", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReferenceOptional, colorOpaqueOnly, {}, "containing the opaque only color buffer for the current frame (at render resolution). Only needed if generating a reactive mask", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReference, depth, {}, "32bit depth values for the current frame (at render resolution).", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReference, motionVectors, {}, "2-dimensional motion vectors (at render resolution if FFX_FSR_ENABLE_DISPLAY_RESOLUTION_MOTION_VECTORS is not set).", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReferenceOptional, exposure, {}, "Optional resource containing a 1x1 exposure value.", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReferenceOptional, reactive, {}, "Optional resource containing alpha value of reactive objects in the scene.", SCHEMA_FLAG_NO_UI)
    //STRUCT_FIELD(NodePinReferenceOptional, transparencyAndComposition, {}, "Optional resource containing alpha value of special objects in the scene.", SCHEMA_FLAG_NO_UI)
    STRUCT_FIELD(NodePinReference, output, {}, "Output color buffer for the current frame (at presentation resolution).", SCHEMA_FLAG_NO_UI)

    STRUCT_FIELD(ValueOrVariable_Float2, jitterOffset, { 0.0f COMMA 0.0f }, "The subpixel jitter offset applied to the camera.", 0)
    STRUCT_FIELD(ValueOrVariable_Float2, motionVectorScale, { 1.0f COMMA 1.0f}, "The scale factor to apply to motion vectors.", 0)

    STRUCT_FIELD(ValueOrVariable_Bool, enableSharpening, { false }, "Enable an additional sharpening pass.", 0)
    STRUCT_FIELD(ValueOrVariable_Float, sharpness, { 1.0f }, "The sharpness value between 0 and 1, where 0 is no additional sharpness and 1 is maximum additional sharpness.", 0)

    STRUCT_FIELD(ValueOrVariable_Float, frameTimeDelta, { 16.67f }, "The time elapsed since the last frame (expressed in milliseconds).", 0)
    STRUCT_FIELD(ValueOrVariable_Float, preExposure, { 1.0f }, "The pre exposure value (must be > 0.0f)", 0)

    STRUCT_FIELD(VariableReference, reset, { }, "A boolean value which when set to true, indicates the camera has moved discontinuously. False if no variable given", 0)

    STRUCT_FIELD(ValueOrVariable_Float, cameraNear, { 0.0f }, "The distance to the near plane of the camera.", 0)
    STRUCT_FIELD(ValueOrVariable_Float, cameraFar, { 1.0f }, "The distance to the far plane of the camera.", 0)

    STRUCT_FIELD(ValueOrVariable_Float, cameraFovAngleVertical, { 0.785398f }, "The camera angle field of view in the vertical direction (expressed in radians).", 0)

    STRUCT_FIELD(ValueOrVariable_Float, viewSpaceToMetersFactor, { 1.0f }, "The scale factor to convert view space units to meters.", 0)

    STRUCT_FIELD(ValueOrVariable_Bool, DRAW_DEBUG_VIEW, { false }, "A boolean variable. False if no variable given. A bit indicating that the output resource will contain debug views with relevant information.", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, NON_LINEAR_COLOR_SRGB, { false }, "A bit indicating that the input color resource contains perceptual sRGB colors", 0)
    STRUCT_FIELD(ValueOrVariable_Bool, NON_LINEAR_COLOR_PQ, { false }, "A bit indicating that the input color resource contains perceptual PQ colors", 0)

    STRUCT_FIELD(ExternalNode_AMD_FidelityFXSDK_Upscaling_GenerateReactiveMask, reactiveMask, {}, "Settings for generating a reactive mask", 0)
STRUCT_END()

VARIANT_BEGIN(ExternalNodeData, "Render graph node variant")
    VARIANT_TYPE(ExternalNode_AMD_FidelityFXSDK_Upscaling, AMD_FidelityFXSDK_Upscaling, {}, "")
VARIANT_END()
